# -*- coding: utf-8 -*-
"""Celcius a Ferenheit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PsyQg6buaSauSFI4OUUwOXpYp3NyWH7n
"""

import tensorflow as tf
import numpy as np

celsius = np.array([-40, -25, -10, 0, 10, 25, 35, 50], dtype = float)
farenheit = np.array([-40, -13, 14, 32, 50, 77, 95, 122], dtype = float)

capa1 = tf.keras.layers.Dense(units = 3, input_shape = [1])
capa2 = tf.keras.layers.Dense(units = 3)
salida = tf.keras.layers.Dense(units=1)
modelo = tf.keras.Sequential([capa1,capa2,salida])

modelo.compile(
    optimizer = tf.keras.optimizers.Adam(0.1),
    loss = "mean_squared_error"
)

print("A punto de entrenar al modelo:")
historia = modelo.fit(celsius, farenheit, epochs = 1000)
print("Modelo ya entrenado...")

predictions = modelo.predict(celsius)
for i in range(len(celsius)):
    print(f"Celsius: {celsius[i]}, Predicción de Fahrenheit: {predictions[i][0]}")

